export interface Product {
  id: string;
  name: string;
  category: string;
  gender: 'men' | 'women' | 'unisex';
  price: number;
  color: string;
  colors: string[];
  sizes: string[];
  description: string;
  image: string;
  stock: number;
}

export const products: Product[] = [
  // Hoodies
  {
    id: 'h1',
    name: 'Classic Oversized Hoodie',
    category: 'hoodies',
    gender: 'unisex',
    price: 1899,
    color: 'Black',
    colors: ['Black', 'Gray', 'Navy', 'White'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    description: 'Comfortable oversized hoodie perfect for everyday wear',
    image: 'https://images.unsplash.com/photo-1556821552-5f2e2f5a9a2b?w=500&h=500&fit=crop',
    stock: 45,
  },
  {
    id: 'h2',
    name: 'Premium Cotton Hoodie',
    category: 'hoodies',
    gender: 'women',
    price: 2299,
    color: 'White',
    colors: ['White', 'Black', 'Pink', 'Blue'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Premium 100% cotton hoodie with embroidered details',
    image: 'https://images.unsplash.com/photo-1556821552-5f2e2f5a9a2b?w=500&h=500&fit=crop',
    stock: 32,
  },
  {
    id: 'h3',
    name: 'Thermal Tech Hoodie',
    category: 'hoodies',
    gender: 'men',
    price: 2799,
    color: 'Navy',
    colors: ['Navy', 'Black', 'Gray'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Thermal technology hoodie for cold weather',
    image: 'https://images.unsplash.com/photo-1556821552-5f2e2f5a9a2b?w=500&h=500&fit=crop',
    stock: 28,
  },
  {
    id: 'h4',
    name: 'College Spirit Hoodie',
    category: 'hoodies',
    gender: 'unisex',
    price: 1599,
    color: 'Gray',
    colors: ['Gray', 'Black', 'Maroon', 'Blue'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    description: 'Casual college-inspired hoodie with trendy designs',
    image: 'https://images.unsplash.com/photo-1556821552-5f2e2f5a9a2b?w=500&h=500&fit=crop',
    stock: 56,
  },

  // Jeans
  {
    id: 'j1',
    name: 'Slim Fit Blue Jeans',
    category: 'jeans',
    gender: 'men',
    price: 2199,
    color: 'Blue',
    colors: ['Blue', 'Black', 'Gray'],
    sizes: ['28', '30', '32', '34', '36', '38'],
    description: 'Classic slim fit jeans in timeless blue',
    image: 'https://images.unsplash.com/photo-1542272604-787c62d465d1?w=500&h=500&fit=crop',
    stock: 67,
  },
  {
    id: 'j2',
    name: 'High Waist Black Jeans',
    category: 'jeans',
    gender: 'women',
    price: 2499,
    color: 'Black',
    colors: ['Black', 'Blue', 'White'],
    sizes: ['24', '26', '28', '30', '32'],
    description: 'Trendy high waist jeans perfect for all occasions',
    image: 'https://images.unsplash.com/photo-1542272604-787c62d465d1?w=500&h=500&fit=crop',
    stock: 43,
  },
  {
    id: 'j3',
    name: 'Distressed Ripped Jeans',
    category: 'jeans',
    gender: 'unisex',
    price: 1999,
    color: 'Light Blue',
    colors: ['Light Blue', 'Dark Blue', 'Black'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Edgy distressed jeans with ripped details',
    image: 'https://images.unsplash.com/photo-1542272604-787c62d465d1?w=500&h=500&fit=crop',
    stock: 34,
  },

  // Trousers
  {
    id: 't1',
    name: 'Formal Black Trousers',
    category: 'trousers',
    gender: 'men',
    price: 2999,
    color: 'Black',
    colors: ['Black', 'Gray', 'Navy'],
    sizes: ['30', '32', '34', '36', '38'],
    description: 'Professional formal trousers for business wear',
    image: 'https://images.unsplash.com/photo-1530268729831-4ca8167eac3f?w=500&h=500&fit=crop',
    stock: 25,
  },
  {
    id: 't2',
    name: 'Casual Khaki Trousers',
    category: 'trousers',
    gender: 'unisex',
    price: 1799,
    color: 'Khaki',
    colors: ['Khaki', 'Gray', 'Beige'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Versatile khaki trousers for casual elegance',
    image: 'https://images.unsplash.com/photo-1530268729831-4ca8167eac3f?w=500&h=500&fit=crop',
    stock: 51,
  },

  // Socks
  {
    id: 's1',
    name: 'Cotton Comfort Socks',
    category: 'socks',
    gender: 'unisex',
    price: 299,
    color: 'White',
    colors: ['White', 'Black', 'Gray', 'Navy'],
    sizes: ['One Size'],
    description: 'Comfortable everyday cotton socks (3-pack)',
    image: 'https://images.unsplash.com/photo-1556821552-a40be9c4cbb7?w=500&h=500&fit=crop',
    stock: 200,
  },
  {
    id: 's2',
    name: 'Premium Wool Socks',
    category: 'socks',
    gender: 'men',
    price: 599,
    color: 'Gray',
    colors: ['Gray', 'Brown', 'Navy'],
    sizes: ['One Size'],
    description: 'Warm merino wool socks for winter (2-pack)',
    image: 'https://images.unsplash.com/photo-1556821552-a40be9c4cbb7?w=500&h=500&fit=crop',
    stock: 120,
  },

  // Shoes
  {
    id: 'sh1',
    name: 'Classic White Sneakers',
    category: 'shoes',
    gender: 'unisex',
    price: 3499,
    color: 'White',
    colors: ['White', 'Black', 'Gray'],
    sizes: ['5', '6', '7', '8', '9', '10', '11', '12', '13'],
    description: 'Timeless white sneakers for all occasions',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500&fit=crop',
    stock: 89,
  },
  {
    id: 'sh2',
    name: 'Womens Running Shoes',
    category: 'shoes',
    gender: 'women',
    price: 4299,
    color: 'Pink',
    colors: ['Pink', 'Purple', 'Black', 'White'],
    sizes: ['5', '6', '7', '8', '9', '10', '11'],
    description: 'High-performance running shoes for women',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500&fit=crop',
    stock: 47,
  },
  {
    id: 'sh3',
    name: 'Black Leather Boots',
    category: 'shoes',
    gender: 'women',
    price: 5499,
    color: 'Black',
    colors: ['Black', 'Brown'],
    sizes: ['5', '6', '7', '8', '9', '10'],
    description: 'Elegant black leather boots for all seasons',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500&fit=crop',
    stock: 32,
  },

  // Tees
  {
    id: 'te1',
    name: 'Graphic T-Shirt',
    category: 'tees',
    gender: 'unisex',
    price: 699,
    color: 'Black',
    colors: ['Black', 'White', 'Gray', 'Navy'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    description: 'Comfortable graphic print t-shirt',
    image: 'https://images.unsplash.com/photo-1516978080064-fbb2c53f6e16?w=500&h=500&fit=crop',
    stock: 120,
  },
  {
    id: 'te2',
    name: 'Premium Cotton Tee',
    category: 'tees',
    gender: 'men',
    price: 899,
    color: 'White',
    colors: ['White', 'Black', 'Blue', 'Gray'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: '100% premium cotton t-shirt',
    image: 'https://images.unsplash.com/photo-1516978080064-fbb2c53f6e16?w=500&h=500&fit=crop',
    stock: 95,
  },

  // Shirts
  {
    id: 'sh4',
    name: 'Casual Button-Up Shirt',
    category: 'shirts',
    gender: 'men',
    price: 1699,
    color: 'Blue',
    colors: ['Blue', 'White', 'Black', 'Striped'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Versatile casual button-up shirt',
    image: 'https://images.unsplash.com/photo-1597070158782-71b205cafed6?w=500&h=500&fit=crop',
    stock: 58,
  },
  {
    id: 'sh5',
    name: 'Womens Blouse',
    category: 'shirts',
    gender: 'women',
    price: 1999,
    color: 'White',
    colors: ['White', 'Black', 'Cream', 'Blush'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Elegant womens blouse for professional settings',
    image: 'https://images.unsplash.com/photo-1597070158782-71b205cafed6?w=500&h=500&fit=crop',
    stock: 41,
  },

  // Jackets
  {
    id: 'ja1',
    name: 'Denim Jacket',
    category: 'jackets',
    gender: 'unisex',
    price: 2499,
    color: 'Blue',
    colors: ['Blue', 'Black', 'Light Blue'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    description: 'Classic denim jacket for timeless style',
    image: 'https://images.unsplash.com/photo-1544922278-58c30eb18914?w=500&h=500&fit=crop',
    stock: 72,
  },
  {
    id: 'ja2',
    name: 'Leather Jacket',
    category: 'jackets',
    gender: 'men',
    price: 5999,
    color: 'Black',
    colors: ['Black', 'Brown'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Premium genuine leather jacket',
    image: 'https://images.unsplash.com/photo-1544922278-58c30eb18914?w=500&h=500&fit=crop',
    stock: 28,
  },
  {
    id: 'ja3',
    name: 'Puffer Winter Jacket',
    category: 'jackets',
    gender: 'women',
    price: 3999,
    color: 'Black',
    colors: ['Black', 'White', 'Navy', 'Red'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Warm puffer jacket with thermal insulation',
    image: 'https://images.unsplash.com/photo-1544922278-58c30eb18914?w=500&h=500&fit=crop',
    stock: 39,
  },
];

export const categories = [
  'hoodies',
  'jeans',
  'trousers',
  'socks',
  'shoes',
  'tees',
  'shirts',
  'jackets',
];

export const genders = ['men', 'women', 'unisex'];
export const colors = [
  'Black',
  'White',
  'Gray',
  'Navy',
  'Blue',
  'Pink',
  'Red',
  'Brown',
  'Green',
  'Purple',
];
